### PR TITLE
feat: add `readAll*` actions to facilitate model reading

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [x] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds the following new hook actions:

- **`readAllSliceModels()`** - Returns all Slice models from all Slice Libraries
- **`readAllSliceModelsForLibrary()`** - Returns all Slice models from a particular Slice Library
- **`readAllCustomTypeModels()`** - Returns all Custom Type models

These actions have been added to facilitate interoperation with `prismic-ts-codegen` to generate TypeScript types. However, the actions can be used in any case where all models are needed.

### SliceMachineActions and SliceMachineHelpers as classes

Both `createSliceMachineActions()` and `createSliceMachineHelpers()` have been refactored to use classes rather than POJOs. Classes made implementing the `readAll*` methods simpler since they could be built using sibling methods.

The move to classes also makes emitting `SliceMachineActions` and `SliceMachineHelpers` types simpler since they are identical to the class type.

### Tests

Tests for the new actions are implemented using a different method than other action tests. Rather than mock a `HookSystem` instance's `callHook` method, the new tests run a full `PluginRunner` instance. Implementing tests this way allows us more granular control over data flow and makes the tests more future proof as implementations change.

To make this work, a new `__debug__` hook type is introduced. The `__debug__` hook is a stub that receives anything and can return anything. It is only to be used for debug purposes, including tests.

[See these lines in `SliceMachineActions-readAllCustomTypes.test.ts` for an example](https://github.com/prismicio/slicemachine-plugin-kit/blob/078fb920f42b8673898e8a5c35693997278d0475/test/SliceMachineActions-readAllCustomTypes.test.ts#L14-L41). In the example, the `__debug__` hook is called to save a reference to `actions`. `actions` is used later in the test outside the context of hooks to test `readAllCustomTypes()`.

**Discussion needed**: This solution could be seen as messy. We need to decide if the `__debug__` solution is worth keeping. It is the most elegant method I could find to test actions.

### Infrastructure changes

This PR also makes the following project infrastructure changes:

- Replaces siroc with Vite + `vite-plugin-sdk`
- Updates all dependencies

## Checklist:

- [ ] My change requires an update to the official documentation.
- [ ] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🐛

### CODE REVIEW

**Comment by angeloashmore** [comment]
## TODO

- [x] Benchmark the `readAll*` actions when multiple plugins with many Slices are registered
- [x] Return hook actions as a property on `pluginRunner` instances. Name it `rawActions` (i.e. `pluginRunner.rawActions`) to dissuade direct usage and add a comment stating not to use it directly (`@deprecated` not necessary). This will let Slice Machine implement an internal `SliceMachineActions` class that can extend the public actions, such as casting types. All internal Slice Machine action usage should go through the internal class, not through `rawActions`
- [x] Remove `__debug__` since we no longer need it. `rawActions` will be accessible on `pluginRunner`, eliminating the need for `__debug__` in tests.

### Notes

- `actions` is created in `createSliceMachineContext`, called in `createSliceMachinePluginRunner.prototype._setupPlugin()`. `_setupPlugin()` is called for each plugin. We can create actions via `createSliceMachineActions` in `SliceMachinePluginRunner`'s constructor and pass it to `createSliceMachineContext` as an argument.

**Comment by angeloashmore** [comment]
# Changes after pair review

- [x] Actions **and** helpers are exported as part of plugin runner instances as `rawActions` and `rawHelpers`. Both are labeled as `@internal` and include TSDoc comments to not use them directly.
- [x] The `__debug__` hook has been removed. It is no longer needed since actions are accessible directly from the plugin runner.
- [x] All action tests have been updated to use the updated strategy.
- [x] Helper tests have been added.

# Benchmark

## Summary

- `*:read` hooks are not affected by the number of registered plugins. This is by design; plugins are not used for `*:read` hooks, only adapters.

- Naturally, all `readAll*` actions are not affected by the number of registered plugins. These actions are built using the `*:read` hooks, thus the `readAll*` actions exhibit similar behavior.

- Hooks that call plugins are directly affected by the number of registered plugins. This behavior is expected.

## Takeaway

I don't think there is a need to optimize hooks or actions at this time, primarily because `*:read` hooks are only registered for the single provided adapter, not any plugins.

Throttling arbitrary plugin calls is not desirable, at least currently. We want to ensure plugins are called atomically in reaction to each Slice Machine event.

## Testing on your own

The benchmark script was added to the `aa/benchmark-actions` branch in the `/benchmark` directory. It's messy. Please don't judge. 🙃

If you see an error in the way the results are measured, please let me know!

**Branch**: https://github.com/prismicio/slicemachine-plugin-kit/tree/aa/benchmark-actions

```sh
cd benchmark
npm i
npm test
```

## Results

- `noPlugins`: A project with an adapter, no plugins.
- `manyPlugins`: A project with an adapter, 1000 plugins (using the same adapter as a plugin)

```
noPlugins#readAllCustomTypeModels x 18609 ops/s
manyPlugins#readAllCustomTypeModels x 18765 ops/s
Fastest is manyPlugins#readAllCustomTypeModels (0.84% faster than runner-up)

noPlugins#readAllSliceModels x 18590 ops/s
manyPlugins#readAllSliceModels x 18600 ops/s
Fastest is manyPlugins#readAllSliceModels (0.05% faster than runner-up)

noPlugins#readAllSliceModelsForLibrary x 18709 ops/s
manyPlugins#readAllSliceModelsForLibrary x 18198 ops/s
Fastest is noPlugins#readAllSliceModelsForLibrary (2.81% faster than runner-up)

noPlugins#slice-library:read x 52050 ops/s
manyPlugins#slice-library:read x 49787 ops/s
Fastest is noPlugins#slice-library:read (4.55% faster than runner-up)

noPlugins#slice:create x 743 ops/s
manyPlugins#slice:create x 406 ops/s
Fastest is noPlugins#slice:create (82.8% faster than runner-up)

noPlugins#slice:read x 25978 ops/s
manyPlugins#slice:read x 26657 ops/s
Fastest is manyPlugins#slice:read (2.61% faster than runner-up)

noPlugins#slice:update x 817 ops/s
manyPlugins#slice:update x 357 ops/s
Fastest is noPlugins#slice:update (128.97% faster than runner-up)

noPlugins#slice:delete x 792 ops/s
manyPlugins#slice:delete x 349 ops/s
Fastest is noPlugins#slice:delete (126.77% faster than runner-up)

noPlugins#custom-type-library:read x 51473 ops/s
manyPlugins#custom-type-library:read x 52531 ops/s
Fastest is manyPlugins#custom-type-library:read (2.05% faster than runner-up)

noPlugins#custom-type:create x 855 ops/s
manyPlugins#custom-type:create x 363 ops/s
Fastest is noPlugins#custom-type:create (135.47% faster than runner-up)

noPlugins#custom-type:read x 27443 ops/s
manyPlugins#custom-type:read x 27340 ops/s
Fastest is noPlugins#custom-type:read (0.38% faster than runner-up)

noPlugins#custom-type:update x 842 ops/s
manyPlugins#custom-type:update x 364 ops/s
Fastest is noPlugins#custom-type:update (131.44% faster than runner-up)

noPlugins#custom-type:delete x 865 ops/s
manyPlugins#custom-type:delete x 360 ops/s
Fastest is noPlugins#custom-type:delete (140.26% faster than runner-up)
```

**Review by lihbr — APPROVED** [review]
LGTM, so what's remaining is the Slice S3-like object storage API, right? Something along those lines perhaps (no `create` yet, same strategy that we had with the screenshot RFC: https://www.notion.so/prismic/RFC-Slice-Machine-Screenshots-af3dcc6d40f447aebc78ad2d790126ed#9b71fe69052b4dddacff721ff376607c)

- `slice:asset:update`
   ```typescript
   type SliceAssetUpdateHookData = {
   	libraryID: string;
   	sliceID: string;
   	asset: {
   		id: string;   // "screenshot.png", could be named "name" also
   		              // but not really consistent with the rest of the API
   		type: string; // "png", or do we want to drop it and let it be inferred from the name?
   		data: Buffer;
   	};
   };
   
   type SliceAssetUpdateHookReturnType = void;
   ```

- `slice:asset:read` (adapter only)
   ```typescript
   type SliceAssetReadHookData = {
   	libraryID: string;
   	sliceID: string;
   	assetID: string; // "screenshot.png"
   };
   
   type SliceAssetUpdateHookReturnType = Buffer; // I assume it throws if the asset doesn't exists,
                                                 // like we do for `slice:read`
   ```

- `slice:asset:delete`
   ```typescript
   type SliceAssetDeleteHookData = {
   	libraryID: string;
   	sliceID: string;
   	assetID: string; // "screenshot.png"
   };
   
   type SliceAssetUpdateHookReturnType = void;
   ```

Buffer might make sense as they refer to memory locations outside of the V8 (which I guess is more performant to have a base64 image manipulated this way than as a string). We'll experiment and see if we want to stay fancy 💅

We could potentially replicate this API when needed for custom types.

**Comment by angeloashmore** [comment]
I think we can rely on the `asset.id` to provide the 

---


We should consider if this asset API is generic or specific to Slices. A generic version of the concept would implement hooks like `asset:update`, `asset:read`, `asset:delete`, which would make it available for any purpose.

**Pros**
- Makes asset management available for any current or future concept that requires saving data.

**Cons**
- Does not have the ability to save files in specific locations (e.g. saving a Slice screenshot in the Slice's directory).
- Makes updating custom screenshots manually (i.e. outside Slice Machine's UI) unergonomic.
- May require saving metadata about local assets, such as custom screenshot names, where we don't persist data today.

Asset saving should be an opaque process.

- Slice Machine requests to save a file.
- The adapter saves it somewhere.
- Slice Machine requests to read a file.

**Comment by angeloashmore** [comment]
I think we can rely on the `asset.id` to provide the 

---


We should consider if this asset API is generic or specific to Slices. A generic version of the concept would implement hooks like `asset:update`, `asset:read`, `asset:delete`, which would make it available for any purpose.

**Pros**
- Makes asset management available for any current or future concept that requires saving data.

**Cons**
- Does not have the ability to save files in specific locations (e.g. saving a Slice screenshot in the Slice's directory).
- Makes updating custom screenshots manually (i.e. outside Slice Machine's UI) unergonomic.
- May require saving metadata about local assets, such as custom screenshot names, where we don't persist data today.

Asset saving should be an opaque process.

- Slice Machine requests to save a file.
- The adapter saves it somewhere.
- Slice Machine requests to read a file.

**Comment by angeloashmore** [comment]
Yes, adding the S3-like asset storage is all that's left based on our discussion.

I think your proposal is what we should move forward with, plus Custom Type support.

I considered an alternative general-purpose set of asset management hooks, but the idea does not seem viable. See **General-purpose asset storage** below.

### TODO

- [ ] Implement `slice:asset*` hooks
- [ ] Implement `custom-type:asset*` hooks (see **Custom Type asset storage** below)

### Slice asset ID + type

I think we should go with just an `id` containing a file extension (e.g. `screenshot.png`).

Using a `type` property to contain a MIME type could be cumbersome to manage. Using file extensions conveys the same information in a more concise way without requiring adapters to convert a type to an extension.

If we consider non-file-system-based adapters that may require a MIME type, the type can be inferred using libraries like [`mime`](https://github.com/broofa/mime).

### General-purpose asset storage

An alternative to the Slice-specific asset hooks is a general-purpose collection of hooks, such as `asset:update` and `asset:read`. Hooks like that would allow Slice Machine to save any data needed without adapters being an implementation bottleneck. If we decide we need to save a new piece of data for each Custom Type, for example, Slice Machine could just save the data in a generic area rather than wait for adapters to implement a new hook.

This comes with a number of drawbacks, however.

- Assets could no longer be saved in logical locations. Slice screenshots, for example, logically belong close to its model and component.
- Name collisions are possible. Without a proper namespacing solution, Slice Machine would need to manage generation of unique IDs. Alternatively, content hashes could be used to semi-guarantee unique IDs, but retrieving that data is not straightforward since the ID cannot be known before the data is retrieved.
- Asset metadata may need to be saved to link general assets to specific data, adding overhead to what should be a simple system.

Thus, a general-purpose collection of asset management hooks does not seem appropriate.

### Custom Type asset storage

We don't need Custom Type-specific asset hooks today, but we may need it in the near future. Saving Custom Type mocks, for example, seems like a logic progression from Slice mocks. Screenshots would follow.

We can support `custom-type:asset:*` today, even if it is not used in Slice Machine until later. Doing so will reduce the burden of updating adapters in the future.

**Comment by angeloashmore** [comment]
I'll merge this PR and implement the asset hooks in a new PR.

**Pull request merged**
